input {

  tcp {

    port => 5000

    codec => json

  }

}

filter {

  mutate {
    add_field => {
      "environment" => "SmartAmal"
    }
  }

  if [logger] =~ /com\.smartamal\.device/ {
    mutate {
      replace => { "service" => "device-service" }
    }
  }

  else if [logger] =~ /com\.smartamal\.notification/ {
    mutate {
      replace => { "service" => "notification-service" }
    }
  }

  else if [logger] =~ /com\.smartamal\.accesscontrol/ {
    mutate {
      replace => { "service" => "access-control-service" }
    }
  }

  else if [logger] =~ /com\.smartamal\.auth/ {
    mutate {
      replace => { "service" => "auth-service" }
    }
  }

  else if [logger] =~ /gateway/ {
    mutate {
      replace => { "service" => "api-gateway" }
    }
  }

  else if [logger] =~ /(netflix\.eureka|netflix\.discovery)/ {
    mutate {
      replace => { "service" => "eureka-server" }
    }
}

  else {
    mutate {
      replace => { "service" => "unknown-service" }
    }
  }

}

output {

  elasticsearch {

    hosts => ["http://elasticsearch:9200"]

    index => "smartamal-logs-%{+YYYY.MM.dd}"

  }

  stdout {

    codec => rubydebug

  }

}
