input {

  tcp {

    port => 5000

    codec => json

  }

}

filter {

  mutate {

    add_field => {

      "environment" => "SmartAmal"

    }

  }

}

output {

  elasticsearch {

    hosts => ["http://elasticsearch:9200"]

    index => "smartamal-logs-%{+YYYY.MM.dd}"

  }

  stdout {

    codec => rubydebug

  }

}